import Head from "next/head";
import Footer from "../components/layout/Footer";

export default function About() {
  return (
    <>
      <Head>
        <title>About Olim</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1 className="content">About</h1>
    </>
  );
}

About.getLayout = function PageLayout(page) {
  return (
    <>
      {page}
      <Footer />
    </>
  );
};
